{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "splash.fullname" . }}
  annotations:
{{- with .Values.hpa.annotations }}
{{- toYaml . | trim | nindent 4 }}
{{- end }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas}}
  minReplicas: {{ .Values.hpa.minreplicas}}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ include "splash.fullname" . }}
  metrics:
  {{- range .Values.hpa.metrics }}
  - type: {{ .type }}
    {{ .type | lower }}:
  {{- if .object }}
      describedObject:
        apiVersion: {{ .object.describedObject.apiVersion }}
        kind: {{ .object.describedObject.kind }}
        name: {{ .object.describedObject.name }}
    {{- if .object.metric }}
      metric: 
        name: {{ .object.metric.name }}
    {{- end }}
    {{- if .object.target }}
      target:
        type: {{ .object.target.type }}
    {{- end }}
    {{- if contains "AverageValue" .object.target.type }}
        averageValue: {{ .object.target.averageValue }}
    {{- else if contains "Value" .object.target.type }}
        value: {{ .object.target.value}}
    {{- else if contains "AverageUtilization" .object.target.type }}
        averageUtilization: {{ .object.target.averageUtilization }}
    {{- end }}
  {{- end }}
  {{- if .external }}
    {{- if .external.metric }}
      metric: 
        name: {{ .external.metric.name }}
        selector:
          matchLabels:
          {{- with .external.metric.selector.matchLabels }}
          {{- toYaml . | trim | nindent 12 }}
          {{- end }}
    {{- end }}
    {{- if .external.target }}
      target:
        type: {{ .external.target.type }}
    {{- end }}
    {{- if contains "AverageValue" .external.target.type }}
        averageValue: {{ .external.target.averageValue }}
    {{- else if contains "Value" .external.target.type }}
        value: {{ .external.target.value}}
    {{- else if contains "AverageUtilization" .external.target.type }}
        averageUtilization: {{ .external.target.averageUtilization }}
    {{- end }}
  {{- end}}
  {{- end }}
{{- end }}