{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splash.fullname" . }}-metrics-config
  labels:
{{ include "splash.labels" . | indent 4 }}
data:
  config.yml: |-
{{ .Values.metrics.config | indent 4}}
{{- end }}