{{- if .Values.ingress.auth.enabled -}}
{{- $fullauthstring := printf "%s:{PLAIN}%s" .Values.ingress.auth.username .Values.ingress.auth.password -}}
apiVersion: v1
data:
  auth: {{ $fullauthstring | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "splash.fullname" . }}
type: Opaque
{{- end }}
